FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install --no-install-recommends \ 
        zsh \ 
        curl \ 
        wget \ 
        unzip \ 
        git \ 
        htop \ 
        micro \
        nano \ 
        --yes && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

WORKDIR /root
COPY . /root/
