FROM ubuntu:20.04

RUN apt update && \
    apt install \ 
        zsh \ 
        curl \ 
        wget \ 
        unzip \ 
        git \ 
        htop \ 
        micro \
        nano \ 
        --yes 

WORKDIR /root
COPY . /root/
