#!/usr/bin/env bash

set -e
# set -x

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
RESETCOLOR=$(tput setaf 7) #white
RESETCOLOR=$(tput sgr0)

# if ! command -v stow &>/dev/null; then
#     echo >&2 "${RED}stow${RESETCOLOR} could not be found"
#     exit 1
# fi

echo "${CYAN}[   1   ]${RESETCOLOR} Copy to home"
echo "${CYAN}[   2   ]${RESETCOLOR} Symlink"
echo "${CYAN}[   3   ]${RESETCOLOR} Delete"
echo "${CYAN}[   4   ]${RESETCOLOR} Copy from home"
echo "${CYAN}[   5   ]${RESETCOLOR} Install oh-my-zsh"
echo "${CYAN}[   6   ]${RESETCOLOR} Install oh-my-zsh plugins"
echo "${CYAN}[ Enter ]${RESETCOLOR} Exit"
echo

read -rp "${YELLOW}Enter a choice: ${RESETCOLOR}" USER_INPUT

if [[ -z $USER_INPUT ]]; then
    exit
fi

IS_NUMBER='^[0-9]+$'
if ! [[ $USER_INPUT =~ $IS_NUMBER ]]; then
    echo >&2 "${RED}Error: Not a valid input${RESETCOLOR}"
    exit 1
fi

if ((USER_INPUT < 1 || USER_INPUT > 6)); then
    echo >&2 "${RED}Error: Not a valid input${RESETCOLOR}"
    exit 1
fi

if [[ $USER_INPUT == 1 ]]; then
    COMMAND="cp --verbose --recursive"
elif [[ $USER_INPUT == 2 ]]; then
    COMMAND="ln --symbolic --verbose --force --relative"
elif [[ $USER_INPUT == 3 ]]; then
    rm -v  ~/.zshrc     
    rm -v  ~/.nanorc   
    rm -v  ~/.gitconfig
    rm -v  ~/.p10k.zsh 
    rm -rf ~/.oh-my-zsh 
    rm -rf ~/.fzf
    exit
elif [[ $USER_INPUT == 4 ]]; then
    cp -vr ~/.zshrc     zshrc     
    cp -vr ~/.nanorc    nanorc    
    cp -vr ~/.gitconfig gitconfig 
    cp -vr ~/.p10k.zsh  p10k.zsh  
    # cp -r  ~/.oh-my-zsh oh-my-zsh 
    exit
elif [[ $USER_INPUT == 5 ]]; then
    if command -v curl &>/dev/null; then
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    elif command -v wget &>/dev/null; then
        sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    elif command -v fetch &>/dev/null; then
        sh -c "$(fetch -o - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"   
    fi
    echo >&2 "${RED}Error: Somehow you don't have ${CYAN}curl wget fetch${RESETCOLOR}"
    exit 1
elif [[ $USER_INPUT == 6 ]]; then
    echo "${CYAN}powerlevel10k${RESETCOLOR}"
    git clone --depth=1 -- https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    #echo "${CYAN}zsh-autocomplete${RESETCOLOR}"
    #git clone --depth=1 -- https://github.com/marlonrichert/zsh-autocomplete.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autocomplete
    echo "${CYAN}zsh-autosuggestions${RESETCOLOR}"
    git clone           -- https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    echo "${CYAN}zsh-syntax-highlighting${RESETCOLOR}"
    git clone           -- https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    exit
fi

#read -p "${YELLOW}Install ${CYAN}oh my zsh${YELLOW}? [y/N]: ${RESETCOLOR}" -n 1 -r
#echo    # (optional) move to a new line
#if [[ $REPLY =~ ^[Yy]$ ]]; then
    # sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    #|| sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    #|| sh -c "$(fetch -o - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    
    #chsh -s $(which zsh)

 #   git clone --depth=1 -- https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  #  git clone --depth=1 -- https://github.com/marlonrichert/zsh-autocomplete.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autocomplete
   # git clone           -- https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    #git clone           -- https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
#fi

${COMMAND} zshrc     ~/.zshrc
${COMMAND} nanorc    ~/.nanorc
${COMMAND} gitconfig ~/.gitconfig
${COMMAND} p10k.zsh  ~/.p10k.zsh
# ${COMMAND} oh-my-zsh ~/.oh-my-zsh

# https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Monofur.zip
# https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
read -p "${YELLOW}Install ${CYAN}fzf${YELLOW}? [y/N]: ${RESETCOLOR}" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
fi
