font_family FiraCode Nerd Font
font_size 14.0
# added in v0.47
auto_reload_config 0.1

shell zsh -lc "tmux attach || tmux"
term tmux-256color

remember_window_size no
initial_window_width 1600
initial_window_height 1000
background_opacity 1.0
dynamic_background_opacity no

scrollback_lines 99999

enable_audio_bell no

startup_session none
enabled_layouts tall
tab_bar_style hidden
tab_bar_show_new_tab_button no
allow_remote_control no

# Disable Kitty tab/window/layout keybindings. These keys pass through to tmux.
map kitty_mod+enter no_op
map cmd+enter no_op
map kitty_mod+n no_op
map cmd+n no_op
map kitty_mod+w no_op
map shift+cmd+d no_op
map kitty_mod+] no_op
map kitty_mod+[ no_op
map kitty_mod+f no_op
map kitty_mod+b no_op
map kitty_mod+` no_op
map kitty_mod+r no_op
map cmd+r no_op
map kitty_mod+1 no_op
map kitty_mod+2 no_op
map kitty_mod+3 no_op
map kitty_mod+4 no_op
map kitty_mod+5 no_op
map kitty_mod+6 no_op
map kitty_mod+7 no_op
map kitty_mod+8 no_op
map kitty_mod+9 no_op
map kitty_mod+0 no_op
map cmd+1 no_op
map cmd+2 no_op
map cmd+3 no_op
map cmd+4 no_op
map cmd+5 no_op
map cmd+6 no_op
map cmd+7 no_op
map cmd+8 no_op
map cmd+9 no_op
map kitty_mod+f7 no_op
map kitty_mod+f8 no_op
map kitty_mod+right no_op
map shift+cmd+] no_op
map ctrl+tab no_op
map kitty_mod+left no_op
map shift+cmd+[ no_op
map ctrl+shift+tab no_op
map kitty_mod+t no_op
map cmd+t no_op
map kitty_mod+q no_op
map cmd+w no_op
map shift+cmd+w no_op
map kitty_mod+. no_op
map kitty_mod+, no_op
map kitty_mod+alt+t no_op
map shift+cmd+i no_op
map kitty_mod+l no_op


# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME
