#!/usr/bin/env sh

menu='select area
focused
all'

selection="$(printf '%s\n' "$menu" | rofi -theme ~/.config/rofi/powermenu.rasi \
    -dmenu -i -monitor 1)"

case $selection in
    "select area") flameshot gui -p ~/Pictures/screenshots;;
    "focused") flameshot screen -p ~/Pictures/screenshots;;
    "all") flameshot full -p ~/Pictures/screenshots;;
esac
