[helpers]

[default]
depends = []

[default.files]
"Preferences.sublime-settings.json" = "~/.config/sublime-text/Packages/User/Preferences.sublime-settings"
"bottom.toml" = "~/.config/bottom/bottom.toml"
# "fonts" =  { target = "~/.local/share/fonts/", type = "symbolic" }
"fonts" = "~/.local/share/fonts/"
gitconfig = "~/.gitconfig"
htoprc = "~/.config/htop/htoprc"
"hyper.js" = "~/.hyper.js"
"microSettings.json" = "~/.config/micro/settings.json"
mpv = "~/.config/mpv"

"terminator.config" = "~/.config/terminator/config"
"wezterm.lua" = "~/.config/wezterm/wezterm.lua"
zshrcZinit = "~/.zshrc"
"starship.toml" = "~/.config/starship.toml"

[default.variables]

[nano4.files]
nanorc4 = "~/.nanorc"
[nano5.files]
nanorc5 = "~/.nanorc"

[p10kClean.files]
"p10kClean.zsh" = "~/.p10k.zsh"
[p10kFancy.files]
"p10kFancy.zsh" = "~/.p10k.zsh"
