# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$battery\
$hostname\
$container\
$username\
$time\
$status\
$cmd_duration\
$line_break\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character\
"""

scan_timeout = 0
command_timeout = 1000
add_newline = false


# Original left and right prompt in 1 line
# format = """
# $battery\
# $container\
# $time\
# $status\
# $cmd_duration\
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $character\
# """

# If we want to use right prompt instead of fill
# right_format = """
# $cmd_duration\
# $status
# $time\
# $battery\
# """
# $sudo\

# # 2 line prompt
# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# \
# $fill\
# $status\
# $cmd_duration\
# $time\
# $battery\
# \
# $line_break\
# $character\
# """
# add_newline = true

[os]
disabled = true

[container]
format = '[\[$name\]]($style) '

[fill]
symbol = " "

[character]
format = "$symbol"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vimcmd_symbol = '[❮](bold yellow) '

[time]
format = '[$time]($style) '
disabled = false
use_12hr = true

[battery]
format =  	"[$symbol$percentage]($style)"

[[battery.display]]
threshold = 100

[status]
# format = '[$symbol $common_meaning$signal_name$maybe_int $status]($style) '
format = '[$symbol $common_meaning$signal_name$maybe_int]($style) '
symbol = ''
# map_symbol = true
# pipestatus = true
disabled = false

[sudo]
disabled = false

[directory]
read_only = " 󰌾"
truncation_length = 8
truncation_symbol = "…/"

[kubernetes]
disabled = true
format = 'on [$symbol$context]($style) '

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count⇣$behind_count"
up_to_date = ""
untracked =	"?$count"
stashed = '\$$count'
modified = "!$count"
staged = "+$count"
renamed = "»$count"
deleted = "✘$count"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
