format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character\
"""


scan_timeout = 0
command_timeout = 1000
add_newline = false

# If we want to use right prompt instead of fill
right_format = """
$status\
$cmd_duration\
$time\
$battery\
"""

# # 2 line prompt
# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# \
# $fill\
# $status\
# $cmd_duration\
# $time\
# $battery\
# \
# $line_break\
# $character\
# """
# add_newline = true


[fill]
symbol = " "

[character]
format = "$symbol"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[time]
disabled = false
use_12hr = true

[battery]
format =  	"[$symbol$percentage]($style)"

[[battery.display]]
threshold = 100

[status]
format = '[$symbol $common_meaning$signal_name$maybe_int]($style) '
map_symbol = true
pipestatus = false
# pipestatus = true
disabled = false
# sigint_symbol = "" # TODO

[directory]
read_only = " "
truncation_length = 8
truncation_symbol = "…/"

[kubernetes]
disabled = true
format = 'on [$symbol$context]($style) '

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count⇣$behind_count"
up_to_date = ""
untracked =	"?$count"
stashed = '\$$count'
modified = "!$count"
staged = "+$count"
renamed = "»$count"
deleted = "✘$count"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

# [os]
# disabled = false
# format = " ($style)"

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
